# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-08-26T00:22:39+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Annotated, Any, Optional
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Stable machine-readable error code")]
    message: str
    details: Optional[dict[str, Any]] = None


class Status(Enum):
    ok = "ok"


class HealthStatus(BaseModel):
    status: Status
    service: str
    version: str


class Tier(Enum):
    starter = "starter"
    growth = "growth"
    pro = "pro"
    enterprise = "enterprise"


class ProgramType(Enum):
    loyalty_stamps = "loyalty_stamps"
    loyalty_points = "loyalty_points"
    membership_pass = "membership_pass"


class RewardMechanic(Enum):
    stamps = "stamps"
    points = "points"


class MembershipValidity(Enum):
    monthly = "monthly"
    quarterly = "quarterly"
    annual = "annual"
    per_event = "per_event"


class PaymentStatus(Enum):
    pending = "pending"
    paid = "paid"
    overdue = "overdue"
    suspended = "suspended"


class Role(Enum):
    platform_admin = "platform_admin"
    merchant_owner = "merchant_owner"
    operation_user = "operation_user"
    customer = "customer"


class Identity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userId: UUID
    email: Optional[EmailStr] = None
    roles: list[Role]
    merchantId: Annotated[
        Optional[UUID],
        Field(None, description="Present for merchant_owner / operation_user."),
    ]
    station: Annotated[
        Optional[str],
        Field(None, description="Operation-user station label (e.g. Caja 1)."),
    ]


class Category(Enum):
    cafe_restaurant = "cafe_restaurant"
    gym = "gym"
    retail = "retail"
    events = "events"
    other = "other"


class Method(Enum):
    card = "card"
    deuna = "deuna"
    manual_transfer = "manual_transfer"


class PaymentSubmission(BaseModel):
    """
    Stubbed payment. For now only manual proof is stored.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    method: Method
    proofStorageKey: Annotated[
        Optional[str],
        Field(
            None,
            description="Private-bucket key of the uploaded receipt, from POST /payment-proofs/upload-url. REQUIRED for `deuna` / `manual_transfer`.\n",
        ),
    ]


class AccountType(Enum):
    savings = "savings"
    checking = "checking"


class PaymentSettings(BaseModel):
    """
    Platform-level transfer/DEUNA account the subscribing merchant pays into. Single record, maintained by platform-admin (Función 04) and read publicly by the signup page (Función 02).

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    configured: Annotated[
        bool,
        Field(
            description="False until platform-admin fills in an account number — the signup page then tells the visitor to contact conpass instead of transferring blind.\n"
        ),
    ]
    bankName: Annotated[Optional[str], Field(None, description="e.g. Banco Pichincha")]
    accountType: Optional[AccountType] = None
    accountNumber: Optional[str] = None
    beneficiaryName: Annotated[
        Optional[str], Field(None, description="Account holder shown to the payer.")
    ]
    beneficiaryTaxId: Annotated[
        Optional[str], Field(None, description="Beneficiary RUC / cédula")
    ]
    contactEmail: Annotated[
        Optional[str],
        Field(None, description="Where payers may also send the receipt."),
    ]
    instructions: Annotated[
        Optional[str],
        Field(None, description="Free-text note rendered under the details."),
    ]
    qrImageUrl: Annotated[
        Optional[str],
        Field(
            None,
            description="Public HTTPS URL of the DEUNA QR image (null until one is uploaded).",
        ),
    ]
    updatedAt: Optional[AwareDatetime] = None


class PaymentSettingsUpdate(BaseModel):
    """
    Partial update. Every field is optional; an explicit empty string clears it. `qrStorageKey` comes from POST /admin/payment-settings/qr-upload-url.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    bankName: Optional[str] = None
    accountType: Optional[AccountType] = None
    accountNumber: Optional[str] = None
    beneficiaryName: Optional[str] = None
    beneficiaryTaxId: Optional[str] = None
    contactEmail: Optional[str] = None
    instructions: Optional[str] = None
    qrStorageKey: Optional[str] = None


class ContentType(Enum):
    image_png = "image/png"
    image_jpeg = "image/jpeg"
    application_pdf = "application/pdf"


class PaymentProofUploadRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contentType: ContentType


class PaymentProofUploadResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    uploadUrl: Annotated[str, Field(description="Short-lived presigned S3 PUT URL.")]
    storageKey: Annotated[str, Field(description="Submit as payment.proofStorageKey.")]


class PaymentProofLink(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[str, Field(description="Short-lived presigned S3 GET URL.")]
    uploadedAt: Optional[AwareDatetime] = None


class ContentType1(Enum):
    image_png = "image/png"
    image_jpeg = "image/jpeg"


class PaymentQrUploadRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contentType: ContentType1


class Subscription(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tier: Tier
    paymentStatus: PaymentStatus
    mrrUsd: float
    activePassLimit: Annotated[
        Optional[int], Field(None, description="Tier cap on active installed passes.")
    ]
    activePassCount: Annotated[
        Optional[int],
        Field(None, description="Billing metric — installed & not deleted."),
    ]
    programLimit: Optional[int] = None
    operationUserLimit: Optional[int] = None
    nextChargeAt: Optional[date] = None
    lastPaymentAt: Optional[date] = None


class SubscriptionUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tier: Optional[Tier] = None
    paymentStatus: Optional[PaymentStatus] = None


class Station(Enum):
    caja_1 = "caja_1"
    caja_2 = "caja_2"
    door_access = "door_access"


class OperationUser(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    name: str
    email: EmailStr
    station: Station
    tempPassword: Annotated[
        Optional[str],
        Field(
            None,
            description="Temporary password, returned only when the operator is first created.",
        ),
    ]


class OperationUserCreate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    email: EmailStr
    station: Station


class OperationUserUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Optional[str] = None
    email: Optional[EmailStr] = None
    station: Optional[Station] = None


class OperationUserPasswordReset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    tempPassword: Annotated[str, Field(description="Newly issued temporary password.")]


class ProgramAppearance(BaseModel):
    """
    Card look. `color` is the pass background colour and is always meaningful: Google Wallet does NOT derive a background from the hero image (it falls back to its own default), so a merchant that wants a specific colour must set one even when an image is used. `backgroundStorageKey` is the hero image drawn ON that colour — the two combine rather than compete, and a transparent PNG lets the colour show through. Empty string clears a field (writes NULL); omitting a field on PATCH leaves it unchanged. The icon is independent of both.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    color: Annotated[
        Optional[str],
        Field(
            None,
            description="Hex background colour of the pass. Empty string clears it. Combines with backgroundStorageKey.",
        ),
    ]
    iconStorageKey: Annotated[
        Optional[str],
        Field(
            None,
            description="Pass logo. PNG, 660x660 minimum, 1:1 (Google Wallet logo spec). Empty string clears it.",
        ),
    ]
    backgroundStorageKey: Annotated[
        Optional[str],
        Field(
            None,
            description="Pass hero image, drawn over the background colour. PNG recommended (a transparent PNG lets the colour show through), 1032x812, ~5:4 — near-square, no embedded text, 20dp breathing room top and bottom (Google Wallet hero-image spec). JPEG accepted. Empty string clears it.",
        ),
    ]
    iconUrl: Annotated[
        Optional[str], Field(None, description="Public URL for the icon (read-only).")
    ]
    backgroundUrl: Annotated[
        Optional[str],
        Field(None, description="Public URL for the background (read-only)."),
    ]


class Kind(Enum):
    icon = "icon"
    background = "background"


class AppearanceUploadRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    contentType: ContentType1


class AppearanceUploadResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    uploadUrl: Annotated[str, Field(description="Presigned S3 PUT URL (short-lived).")]
    storageKey: Annotated[
        str, Field(description="S3 key to persist via PATCH /programs appearance.")
    ]
    publicUrl: Annotated[
        str, Field(description="Public HTTPS URL for the uploaded asset.")
    ]


class Wallet(Enum):
    apple = "apple"
    google = "google"


class ProgramCreate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: ProgramType
    name: str
    mechanic: Optional[RewardMechanic] = None
    stampsForReward: Annotated[Optional[int], Field(None, ge=1)]
    pointsForReward: Annotated[Optional[int], Field(None, ge=1)]
    pointsPerDollar: Annotated[Optional[float], Field(None, ge=0.0)]
    reward: Annotated[
        Optional[str], Field(None, description="Reward description shown on the card.")
    ]
    membershipValidity: Optional[MembershipValidity] = None
    membershipIncludes: Optional[str] = None
    welcomeBonus: Optional[int] = 0
    expiryDays: Annotated[
        Optional[int],
        Field(None, description="Balance expiry window; null = no expiry."),
    ]
    appearance: ProgramAppearance
    wallets: Annotated[list[Wallet], Field(min_length=1)]


class ProgramUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Optional[str] = None
    reward: Optional[str] = None
    stampsForReward: Annotated[Optional[int], Field(None, ge=1)]
    pointsForReward: Annotated[Optional[int], Field(None, ge=1)]
    pointsPerDollar: Annotated[Optional[float], Field(None, ge=0.0)]
    appearance: Optional[ProgramAppearance] = None
    active: Optional[bool] = None


class Program(ProgramCreate):
    id: UUID
    merchantId: UUID
    active: bool
    enrollmentUrl: Optional[AnyUrl] = None
    createdAt: AwareDatetime


class Language(Enum):
    """
    UI language the customer had selected when submitting the form; drives the labels on their wallet pass. Omitted means Spanish. Deliberately carries no OpenAPI `default`: datamodel-codegen emits one as a bare string rather than an enum member, so every request model would fail its own enum on serialization. The fallback lives in the handler instead.
    """

    es = "es"
    en = "en"


class EnrollmentRequest(BaseModel):
    """
    Minimal PII by design; all personal fields optional.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    fullName: Optional[str] = None
    email: Optional[EmailStr] = None
    phone: Annotated[Optional[str], Field(None, description="WhatsApp number.")]
    birthday: Optional[date] = None
    accessCode: Annotated[
        Optional[str],
        Field(None, description="Required for exclusive/membership programs."),
    ]
    consent: Annotated[
        Optional[bool], Field(None, description="Consent to WhatsApp/email comms.")
    ]
    dedupeKey: Annotated[
        Optional[str],
        Field(
            None,
            description="Optional client key to dedupe repeat submissions from the same device.",
        ),
    ]
    language: Annotated[
        Optional[Language],
        Field(
            None,
            description="UI language the customer had selected when submitting the form; drives the labels on their wallet pass. Omitted means Spanish. Deliberately carries no OpenAPI `default`: datamodel-codegen emits one as a bare string rather than an enum member, so every request model would fail its own enum on serialization. The fallback lives in the handler instead.",
        ),
    ]


class Language1(Enum):
    es = "es"
    en = "en"


class Balance(BaseModel):
    """
    Backend-authoritative. Wallet is display-only.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mechanic: RewardMechanic
    stamps: Annotated[Optional[int], Field(None, ge=0)]
    stampsForReward: Optional[int] = None
    points: Annotated[Optional[int], Field(None, ge=0)]
    pointsForReward: Optional[int] = None
    rewardsAvailable: Annotated[
        Optional[int],
        Field(None, description="Rewards earned and not yet claimed.", ge=0),
    ]
    rewardsRedeemed: Annotated[
        Optional[int],
        Field(None, description="Rewards already claimed — never decreases.", ge=0),
    ]
    membershipActiveUntil: Optional[date] = None


class WalletLinks(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    google: Annotated[
        Optional[AnyUrl],
        Field(None, description="Add to Google Wallet (signed JWT save link)."),
    ]
    apple: Annotated[
        Optional[AnyUrl],
        Field(None, description="Add to Apple Wallet (.pkpass) — future."),
    ]


class ScanResolveRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[
        str, Field(description="Scanned opaque token or manually-entered code.")
    ]


class AccrueRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cardId: UUID
    operationUserId: UUID
    stamps: Annotated[
        Optional[int], Field(None, description="Stamps to add (stamps mechanic).", ge=1)
    ]
    amount: Annotated[
        Optional[float],
        Field(None, description="Purchase amount → points (points mechanic).", ge=0.0),
    ]
    occurredAt: Annotated[
        Optional[AwareDatetime],
        Field(
            None,
            description="Client timestamp of the in-store event (for offline replay ordering).",
        ),
    ]


class RedeemRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cardId: UUID
    operationUserId: UUID
    occurredAt: Optional[AwareDatetime] = None


class ValidateAccessRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cardId: UUID
    operationUserId: UUID
    occurredAt: Optional[AwareDatetime] = None


class Kind1(Enum):
    accrue_stamps = "accrue_stamps"
    accrue_points = "accrue_points"
    redeem = "redeem"
    validate_access = "validate_access"
    birthday_issue = "birthday_issue"


class Transaction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    cardId: UUID
    kind: Kind1
    stampsDelta: Optional[int] = None
    pointsDelta: Optional[int] = None
    operationUserId: Optional[UUID] = None
    idempotencyKey: Optional[UUID] = None
    createdAt: AwareDatetime


class AccessDecision(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cardId: UUID
    granted: bool
    reason: Optional[str] = None
    validUntil: Optional[date] = None


class Redemption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    customerName: str
    customerPhone: Optional[str] = None
    customerEmail: Optional[EmailStr] = None
    programId: UUID
    program: Optional[str] = None
    reward: str
    redeemedAt: AwareDatetime


class ProgramMetrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    secondVisitRate30d: Annotated[
        Optional[float],
        Field(None, description="% of new customers returning within 30d."),
    ]
    activeInstalledPasses: Optional[int] = None
    installsThisWeek: Optional[int] = None
    visits: Optional[int] = None
    redemptions: Optional[int] = None
    churnRate: Annotated[Optional[float], Field(None, description="% passes deleted.")]
    eligibleForReminder: Annotated[
        Optional[int], Field(None, description="Customers 1 stamp/step from reward.")
    ]


class BenefitType(Enum):
    discount = "discount"
    gift = "gift"


class BirthdayAutomation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool
    benefitType: BenefitType
    discountPercent: Annotated[Optional[int], Field(None, ge=1, le=100)]
    gift: Optional[str] = None
    validityDays: Annotated[Optional[int], Field(None, ge=1)]


class BirthdayCardCreate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    programId: UUID
    customerId: UUID


class Status1(Enum):
    pending = "pending"
    issued = "issued"
    redeemed = "redeemed"
    expired = "expired"


class BirthdayCard(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    code: Annotated[
        str, Field(description="Unique irreproducible code (e.g. CUMPLE-3F9A).")
    ]
    customerName: str
    benefit: Optional[str] = None
    validUntil: Optional[date] = None
    status: Status1
    walletLinks: Optional[WalletLinks] = None


class AdminClient(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    merchantId: UUID
    name: str
    city: str
    tier: Tier
    paymentStatus: PaymentStatus
    mrrUsd: float
    since: Optional[date] = None
    nextChargeAt: Optional[date] = None
    lastPaymentAt: Optional[date] = None
    hasPaymentProof: Annotated[
        Optional[bool],
        Field(
            None,
            description="True when the client uploaded a manual-transfer receipt at signup — the admin can then open it via GET /admin/clients/{merchantId}/payment-proof.\n",
        ),
    ]
    paymentProofUploadedAt: Optional[AwareDatetime] = None


class PlatformStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activeClients: int
    mrrUsd: float
    growthCount: Optional[int] = None
    starterCount: Optional[int] = None
    overdueCount: Optional[int] = None


class Segment(Enum):
    one_step_from_reward = "one_step_from_reward"
    inactive_30d = "inactive_30d"
    birthday = "birthday"


class Channel(Enum):
    push = "push"
    whatsapp = "whatsapp"


class ReminderRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    programId: UUID
    segment: Optional[Segment] = "one_step_from_reward"
    channel: Optional[Channel] = "push"


class ReminderResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    queued: Annotated[int, Field(description="Recipients queued.")]
    provider: Annotated[Optional[str], Field(None, description="For now: 'stub'.")]


class DemoContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    merchantId: UUID
    businessName: str
    programId: Annotated[
        UUID,
        Field(
            description="Latest program of the demo merchant — the public enroll journey targets it."
        ),
    ]
    ownerEmail: EmailStr
    ownerPassword: Annotated[
        str,
        Field(
            description="Shared demo password — intentionally public (sandbox account, demo-only data)."
        ),
    ]


class MerchantOnboardRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    businessName: str
    ruc: Annotated[str, Field(description="Ecuador tax id")]
    category: Category
    city: str
    contactName: str
    contactEmail: EmailStr
    tier: Tier
    payment: PaymentSubmission


class Merchant(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    businessName: str
    ruc: Optional[str] = None
    category: str
    city: str
    contactName: Optional[str] = None
    contactEmail: Optional[EmailStr] = None
    logoStorageKey: Optional[str] = None
    subscription: Optional[Subscription] = None
    createdAt: AwareDatetime


class Card(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    programId: UUID
    merchantId: UUID
    customerId: Optional[UUID] = None
    type: ProgramType
    opaqueToken: Annotated[
        Optional[str],
        Field(None, description="Opaque per-member id encoded in the QR."),
    ]
    balance: Balance
    holderName: Annotated[
        Optional[str], Field(None, description='Display name (e.g. "María T.").')
    ]
    language: Optional[Language1] = None
    active: bool
    walletInstalled: Annotated[
        Optional[bool],
        Field(None, description="Drives the active-pass billing metric."),
    ]
    createdAt: AwareDatetime


class CardIssued(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    card: Card
    walletLinks: WalletLinks


class CardResolution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    card: Card
    program: Program


class OperationResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    card: Card
    transaction: Transaction
    walletUpdateQueued: Optional[bool] = None


class MerchantOnboardResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    merchant: Merchant
    subscription: Subscription
    ownerInviteSent: bool
    ownerEmail: Annotated[
        Optional[EmailStr],
        Field(None, description="Login email for the owner account."),
    ]
    ownerTempPassword: Annotated[
        Optional[str],
        Field(
            None,
            description="Temporary password for first login (shown once on the activation screen, per Función 03). The owner should change it after logging in.\n",
        ),
    ]
